In [7]:
import pandas as pd

In [8]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/openlifescienceai/medmcqa/" + splits["train"])
df.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
0,e9ad821a-c438-4965-9f77-760819dfa155,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,2,single,Chronic urethral obstruction because of urinar...,Anatomy,Urinary tract
1,e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,2,single,Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...,Biochemistry,Vitamins and Minerals
2,5c38bea6-787a-44a9-b2df-88f4218ab914,All of the following are surgical options for ...,Adjustable gastric banding,Biliopancreatic diversion,Duodenal Switch,Roux en Y Duodenal By pass,3,multi,"Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...",Surgery,Surgical Treatment Obesity
3,cdeedb04-fbe9-432c-937c-d53ac24475de,Following endaerectomy on the right common car...,Central aery of the retina,Infraorbital aery,Lacrimal aery,Nasociliary aretry,0,multi,The central aery of the retina is a branch of ...,Ophthalmology,None
4,dc6794a3-b108-47c5-8b1b-3b4931577249,Growth hormone has its effect on growth through?,Directly,IG1-1,Thyroxine,Intranuclear receptors,1,single,"Ans. is 'b' i.e., IGI-1GH has two major functi...",Physiology,None

In [9]:
treatment

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
67,1d4ccb9d-1924-4aa6-b07c-0ed46fe31c20,Which of the following is the best procedure d...,Fetal echocardiography,Fetal scalp pH,Continuous electrical fetal hea monitoring,Physical examination,2,single,Electrical Fetal hea monitoring is useful as: ...,Gynaecology & Obstetrics,"Intra Uterine Growth Restriction, Intrapaum an..."
99,aeb420c2-ede8-48bc-9400-a5ae531f15ee,The radiograph of a 32 year old patient is sho...,Stafne’s bone cavity,Radicular Cyst,Dentigerous cyst,Lateral periodontal cyst,0,single,Radiological signs:\nThe lesion presents as a ...,Radiology,None
123,31868f6c-233a-40ee-880e-9c668509a8b1,An ill 16 days old baby girl is brought to the...,CHF,Glycogen storage disease,Pericarditis,Aberrant left coronary aery arising from pulmo...,0,multi,"In CHF pallor, dyspnoea, tachypnoea, tachycard...",Pediatrics,Impoant Viral Diseases in Children
177,62f6d5bb-6085-4328-97a0-3e3776f9ae78,A patient with cushinoid features presents wit...,Adrenal hyperplasia,Adrenal adenoma,Ca lung with ectopic ACTH production,Pituitary microadenoma,2,single,Answer is C (Ca lung with ectopic ACTH product...,Medicine,None
226,cbd91783-e901-4672-9ec1-7f58bce041da,A 74-year-old woman develops occipital headach...,basal ganglia hemorrhage,cerebellar hemorrhage,pontine hemorrhage,lobar intracerebral hemorrhage,1,multi,"Cerebellar hemorrhage, when mild, may present ...",Medicine,C.N.S.
...,...,...,...,...,...,...,...,...,...,...,...
182681,a14b3941-8e39-4751-a11d-bd6902347986,Best treatment of old fracture is,Manipulation and POP cast application.,Open reduction and internal fixation and bone ...,K Wire fixation,External fixation,1,single,Nonunion fracture shaft femur requires open re...,Unknown,None
182684,cee3c1f1-c97b-4f39-a23d-da191d9923d3,A 10-year old boy presents to the pediatric em...,Takayasu's aooaeritis,Renal parenchymal disease,Grand mal seizures,Coarctation of aoa,3,single,Isolated upper extremity hypeension (200/140 m...,Medicine,All India exam
182698,61d9c55c-2527-4bf5-ba6e-083cb2b9a24b,"Lalita, a female patient presents with pigment...",Carcinoid tumor,Melanoma,Villous adenoma,Peutz-Jegher's syndrome,3,single,The polyps of Peutz-Jeghers syndrome are gener...,Surgery,Large intestine
182711,752ef035-386a-4803-af5a-af7a5dc9357d,"Best treatment of 3 weeks old, fracture shaft ...",Bone graft with internal fixation,External fixation,Internal fixation only,Prosthesis,0,single,None,Orthopaedics,None
182809,865375da-5bbd-43a3-b921-7959f2c6c5c7,A patient with psoriasis was staed on systemic...,Bacterial infection,Erythrodermic Psoriasis,Drug induced reaction,Pustular psoriasis,3,multi,Patient of psoriasis on withdrawal of systemic...,Dental,Psoriasis

In [10]:
treatment = df.loc[df['question'].str.contains('treatment|procedure|diagnosis|medicat') & df['question'].str.contains('infant|child|patient|man|boy|girl|male|year|procedure|old|senior')]
treatment['question'].to_csv('treatment_questions.csv')
# agarrar conjunto de ~200 ver que preguntas son buenas, tambien ver las que dejamos afuera
# podes comparar vs chatgpt cuales no funcionan.
# agarrar subconjuntos por tipo de subject_name
treatment.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
67,1d4ccb9d-1924-4aa6-b07c-0ed46fe31c20,Which of the following is the best procedure d...,Fetal echocardiography,Fetal scalp pH,Continuous electrical fetal hea monitoring,Physical examination,2,single,Electrical Fetal hea monitoring is useful as: ...,Gynaecology & Obstetrics,"Intra Uterine Growth Restriction, Intrapaum an..."
99,aeb420c2-ede8-48bc-9400-a5ae531f15ee,The radiograph of a 32 year old patient is sho...,Stafne’s bone cavity,Radicular Cyst,Dentigerous cyst,Lateral periodontal cyst,0,single,Radiological signs:\nThe lesion presents as a ...,Radiology,None
123,31868f6c-233a-40ee-880e-9c668509a8b1,An ill 16 days old baby girl is brought to the...,CHF,Glycogen storage disease,Pericarditis,Aberrant left coronary aery arising from pulmo...,0,multi,"In CHF pallor, dyspnoea, tachypnoea, tachycard...",Pediatrics,Impoant Viral Diseases in Children
177,62f6d5bb-6085-4328-97a0-3e3776f9ae78,A patient with cushinoid features presents wit...,Adrenal hyperplasia,Adrenal adenoma,Ca lung with ectopic ACTH production,Pituitary microadenoma,2,single,Answer is C (Ca lung with ectopic ACTH product...,Medicine,None
226,cbd91783-e901-4672-9ec1-7f58bce041da,A 74-year-old woman develops occipital headach...,basal ganglia hemorrhage,cerebellar hemorrhage,pontine hemorrhage,lobar intracerebral hemorrhage,1,multi,"Cerebellar hemorrhage, when mild, may present ...",Medicine,C.N.S.

In [11]:
treatment.to_csv("treatment.csv")